### ISSUE TITLE
ESP32 Loader

### ISSUE THREAD

**Issue by kubo6472** [iotappstory/ESP8266-Loader#1]
Not an issue. Just a question. How to do this on ESP32 ? I am little bit confused with your documentation as you support ESP32 but every tutorial or something helpful goes just to esp8266. btw. I am using Platformio in Atom.

**Comment by Onno-Dirkzwager** [comment]
Hi kubo6472,
we missed this issue, our apologies!

If you are still interested, we have recently released version 2.0.0 with full support for the esp32
